### ISSUE TITLE
TypeError: Can't convert element 2 (19) to hsize_t

### ISSUE THREAD

**Issue by linrio** [Rochester-NRT/AlphaGo#82]
In the **Feature conversion script**, I run `# python -m AlphaGo.preprocessing.game_converter -f all -o outfile/ -R -d tests/test_data/sgf/ -s 19 -v`  . It shows the error: 
_using features ['board', 'ones', 'turns_since', 'liberties', 'capture_size', 'self_atari_size', 'liberties_after', 'sensibleness', 'zeros']
sgfs_to_hdf5 failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lingfeng/alphago/AlphaGo-develop/AlphaGo/preprocessing/game_converter.py", line 218, in <module>
    run_game_converter()
  File "/home/lingfeng/alphago/AlphaGo-develop/AlphaGo/preprocessing/game_converter.py", line 214, in run_game_converter
    converter.sgfs_to_hdf5(files, args.outfile, bd_size=args.size, verbose=args.verbose)
  File "/home/lingfeng/alphago/AlphaGo-develop/AlphaGo/preprocessing/game_converter.py", line 133, in sgfs_to_hdf5
    raise e
TypeError: Can't convert element 2 (19) to hsize_t
_

**TypeError: Can't convert element 2 (19) to hsize_t**

How to solve this problem?

**Comment by linrio** [comment]
_[root@lf AlphaGo-develop]# python -m AlphaGo.preprocessing.game_converter -h
usage: game_converter.py [-h] [--features FEATURES] --outfile OUTFILE
                         [--recurse] [--directory DIRECTORY] [--size SIZE]
                         [--verbose]

Prepare SGF Go game files for training the neural network model.

optional arguments:
  -h, --help            show this help message and exit
  --features FEATURES, -f FEATURES
                        Comma-separated list of features to compute and store
                        or 'all'
  --outfile OUTFILE, -o OUTFILE
                        Destination to write data (hdf5 file)
  --recurse, -R         Set to recurse through directories searching for SGF
                        files
  --directory DIRECTORY, -d DIRECTORY
                        Directory containing SGF files to process. if not
                        present, expects files from stdin
  --size SIZE, -s SIZE  Size of the game board. SGFs not matching this are
                        discarded with a warning
  --verbose, -v         Turn on verbose mode

Available features are: board, ones, turns_since, liberties, capture_size,
self_atari_size, liberties_after, sensibleness, and zeros. Ladder features are
not currently implemented
_

**Comment by linrio** [comment]
[root@lf AlphaGo-develop]# `python -m AlphaGo.preprocessing.game_converter -h`
usage: game_converter.py [-h] [--features FEATURES] --outfile OUTFILE
                         [--recurse] [--directory DIRECTORY] [--size SIZE]
                         [--verbose]

Prepare SGF Go game files for training the neural network model.

optional arguments:
  -h, --help            show this help message and exit
  --features FEATURES, -f FEATURES
                        Comma-separated list of features to compute and store
                        or 'all'
  --outfile OUTFILE, -o OUTFILE
                        Destination to write data (hdf5 file)
  --recurse, -R         Set to recurse through directories searching for SGF
                        files
  --directory DIRECTORY, -d DIRECTORY
                        Directory containing SGF files to process. if not
                        present, expects files from stdin
  --size SIZE, -s SIZE  Size of the game board. SGFs not matching this are
                        discarded with a warning
  --verbose, -v         Turn on verbose mode

Available features are: board, ones, turns_since, liberties, capture_size,
self_atari_size, liberties_after, sensibleness, and zeros. Ladder features are
not currently implemented
