### ISSUE TITLE
missing self-atari in game

### ISSUE THREAD

**Issue by thouis** [Rochester-NRT/AlphaGo#83]
At move 83, Black @ S9 would be a self-atari of 4 stones, but this feature is not showing up in the self-atari features.

[game.zip](https://github.com/Rochester-NRT/AlphaGo/files/203363/game.zip)

**Comment by thouis** [comment]
Looking closer, it's registering as a self-atari of size 2, rather than 4.

**Comment by thouis** [comment]
In the same game, at move 85, white has a capture at move 85 of 3 stones at S9 which isn't being detected.

**Comment by linrio** [comment]
@thouis  In the step of feature conversion script : # p`ython -m AlphaGo.preprocessing.game_converter`
how much of your -s SIZE parameter?

**Comment by thouis** [comment]
The default.

**Comment by linrio** [comment]
@thouis Got.Thanks

**Comment by linrio** [comment]
@thouis  And in the step of **Supervised training script**. When I run E**xample 1: train on mini dataset created above and save results to training_results/**, it shows error:
_[root@lf AlphaGo-develop]# python -m AlphaGo.training.supervised_policy_trainer ./tests/test_data/minimodel.json test_features.hdf5 training_results/ --epochs 5 --minibatch 32 --learning-rate 0.01
Using Theano backend.
/home/linrio/alphago/AlphaGo-develop/AlphaGo/training/supervised_policy_trainer.py:179: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  train_indices = shuffle_indices[0:n_train_data]
/home/linrio/alphago/AlphaGo-develop/AlphaGo/training/supervised_policy_trainer.py:180: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val_indices = shuffle_indices[n_train_data:n_train_data + n_val_data]
Epoch 1/5
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/linrio/alphago/AlphaGo-develop/AlphaGo/training/supervised_policy_trainer.py", line 215, in <module>
    run_training()
  File "/home/linrio/alphago/AlphaGo-develop/AlphaGo/training/supervised_policy_trainer.py", line 212, in run_training
    nb_worker=args.workers)
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/models.py", line 1149, in fit_generator
    class_weight=class_weight)
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/models.py", line 827, in train_on_batch
    return self._train(ins)
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/backend/theano_backend.py", line 446, in __call__
    return self.function(*inputs)
  File "/usr/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
**ValueError: CorrMM images and kernel must have the same stack size**

Apply node that caused the error: CorrMM{half, (1, 1)}(<TensorType(float32, 4D)>, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 49
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(32, 46, 19, 19), (16, 12, 5, 5)]
Inputs strides: [(66424, 1444, 76, 4), (1200, 100, -20, -4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{add,no_inplace}(CorrMM{half, (1, 1)}.0, Reshape{4}.0), Elemwise{Composite{(i0 * (Abs(i1) + i2 + i3))}}[(0, 2)](TensorConstant{(1, 1, 1, 1) of 0.5}, Elemwise{add,no_inplace}.0, CorrMM{half, (1, 1)}.0, Reshape{4}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/layers/convolutional.py", line 310, in get_output
    X = self.get_input(train)
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/layers/convolutional.py", line 310, in get_output
    X = self.get_input(train)
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/layers/convolutional.py", line 310, in get_output
    X = self.get_input(train)
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/layers/convolutional.py", line 315, in get_output
    filter_shape=self.W_shape)
  File "/usr/lib/python2.7/site-packages/Keras-0.3.3-py2.7.egg/keras/backend/theano_backend.py", line 692, in conv2d
    filter_shape=filter_shape)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
_

And what`s this problem?

**Comment by wrongu** [comment]
@linrio must be another windows thing. Can you try changing the `np.floor(...)` on line 128 of that file to `int(...)` ? If that works, please open a PR with it. Thanks!

**Comment by linrio** [comment]
I never modify np.floor() ::
 `128         n_train_data = np.floor(args.train_val_test[0] * n_total_data)`

**Comment by wrongu** [comment]
I'm suggesting that you modify it to see if that fixes the problem

**Comment by linrio** [comment]
@wrongu how to midify it?

**Comment by linrio** [comment]
@wrongu  Now I modify 
_  128         n_train_data = np.int(args.train_val_test[0] * n_total_data)_
_  129         n_val_data = np.int(args.train_val_test[1] * n_total_data)_

A

**Comment by linrio** [comment]
@wrongu I do not install cuda.Is this the reason of bug?

**Comment by wrongu** [comment]
@linrio hm. it's not obvious what the bug is. If you join the [gitter](https://gitter.im/Rochester-NRT/AlphaGo) chat, we can try to debug there

**Comment by linrio** [comment]
@wrongu Ok, Thanks!

**Comment by LJY2345** [comment]
Google good powerful!。。。
